### ISSUE TITLE
failure to close Keithley6500 crashes measurement

### ISSUE THREAD

**Issue by bschiela** [ShabaniLab/LabberDrivers#5]
![image](https://user-images.githubusercontent.com/7977337/130363138-3fc97ac0-1cb2-4302-a985-99f21cda29e8.png)

possibly due to a network interruption...consider adding retry logic

**Comment by bschiela** [comment]
seems to have coincided with LakeShore communication failure.  both occurred Saturday ~midnight during heavy rains from tropical storm Henri

![image](https://user-images.githubusercontent.com/7977337/130466607-61cb82f7-3c37-4a0e-bfe6-250741cd3922.png)

**Comment by bschiela** [comment]
problem recurred around 4-5pm today, during scan JS512-C09_FlSq4to1-8_FlSq4to7_WFS02_166.  temperatures appear stagnant, will check LakeShore display tomorrow

![image](https://user-images.githubusercontent.com/7977337/131070547-827c880d-2ecc-4dd9-9928-5f8f1ca34085.png)

**Comment by bhe220** [comment]
Same error on the lakeshore again. Happens on all fridges at the same time even when labber  isn't running (a measurement or even connected to instruments).

**Comment by bschiela** [comment]
didn't find anything useful in the logs...

`grep -i lakeshore 'CoolerSysLog 210716 214501'*`

[CoolerSysLog 210716 214501_2.slg.txt](https://github.com/ShabaniLab/LabberDrivers/files/7079077/CoolerSysLog.210716.214501_2.slg.txt)
[CoolerSysLog 210716 214501.slg.txt](https://github.com/ShabaniLab/LabberDrivers/files/7079078/CoolerSysLog.210716.214501.slg.txt)

**Comment by bschiela** [comment]
error occurred 3rd time on Aug 29, ~8:40pm

**Comment by bschiela** [comment]
the cold head motor on the microwave fridge cryomech compressor also got knocked out on Aug 29, chalking it up to power surges/grid instability

**Comment by joeyuan19** [comment]
Re: cryomech motor issue, fixed by power cycling compressor via main breaker on compressor unit.
